### ISSUE TITLE
WebConstants.SPRING_PROCESS_SAVED_REQUEST

### ISSUE THREAD

**Issue by dlhf** [shimingxy/MaxKey#8]
WebConstants.SPRING_PROCESS_SAVED_REQUEST don't exist

**Comment by dlhf** [comment]
https://github.com/shimingxy/MaxKey/blob/239573cd0594894c1cb08e51a91c3964df125a72/maxkey-web-manage/src/main/java/org/maxkey/web/endpoint/LoginEndpoint.java#L100

**Comment by shimingxy** [comment]
5/23  fixed，已经修复
